### ISSUE TITLE
Create a notebook to demo slow removal of water

### ISSUE THREAD

**Issue by vengroff** [vengroff/censusdis#138]
Following up on #110 and the PR https://github.com/geopandas/geopandas/pull/2939, put the example of NY water removal into a notebook. Probably save it with a smaller state so it runs in the 300 second nbmake limit, but with a comment showing where to toggle it to NY to take longer. Use the time magic to track the time.

**Comment by audreymarthin** [comment]
Hi Darren,

I am Audrey Marthin and I just started the TwoSigma College Mentor Connect program. My mentor have chosen your open source project for me, and I'm excited to explore and develop your project as well. This will be my first issue that I will work on. Thank you!

**Comment by vengroff** [comment]
Hi Audrey. Welcome to the project. I look forward to seeing your work. By all means reach out to me with any questions that come up along the way.

**Comment by audreymarthin** [comment]
Hi Darren. Thank you! I will definitely reach out to you, looking forward to working with you.

**Comment by audreymarthin** [comment]
Hi Darren, I wanted to ask a few clarifying questions about my understanding of the task. In this issue, I will have to show that the removal of water is slow utilizing some time magic to track the time. However, I will save this notebook in a smaller state so that it will finish within the time limit. Then, I should also comment on where users will be able to change states and test the water removal for NY as well. Is this understanding correct of the task?

Thank you Darren!

**Comment by vengroff** [comment]
Yes, I think that's a good summary.

Thanks for taking this on.

**Comment by audreymarthin** [comment]
It's my pleasure!

**Comment by audreymarthin** [comment]
Hi Darren, I have made the notebook for this issue and have opened up a pull request. Thank you!

**Comment by vengroff** [comment]
#144 was merged.
