### ISSUE TITLE
Extend `censusdis.datasets` to include more data sets

### ISSUE THREAD

**Issue by vengroff** [vengroff/censusdis#143]
Right now [`censusdis/datasets.py`](https://github.com/vengroff/censusdis/blob/main/censusdis/datasets.py) only has a small number of symbols. In fact, it only has two. But even in our demo notebooks and unit tests we use more datasets than that. It would be ideal if all of the datasets we use across the project had symbolic names in `datasets.py`. And even better if all the notebooks and unit tests referred to them by these names. 

There are over 1,000 data sets, so we won't get names for all of them in here. A good summary of the popular ones can be found at https://www.census.gov/data/developers/data-sets.html. It would be nice to have symbolic names for most of those, and and integration test that verifies that each of them can be recognize when used in a basic query.

No matter how far you take a solution to this issue, whether you end up adding 5 new constants or hundreds, it would be nice to add more to the docstring of the `censusdis.datasets` module to explain that the purpose of this file is to give symbolic names for commonly used data sets. It should never be considered authoritative in terms of the full collection of data sets available. New data sets and vintages are added all the time and `censusdis` can, for the most part, just use them out of the box with no changes.  In order to get an exhaustive and up to the minute accurate list of available data sets, call `censusdis.data.variables.all_data_sets()`.

**Comment by audreymarthin** [comment]
Hi Darren, 

I will work on this issue next. Right now, my approach is adding functions needed to query the datasets and parsing the results into a variable, which will all be in datasets.py. The variables will store the symbolic names and urls. I was wondering about your thoughts on this approach?

Thank you!

**Comment by dat-sudo** [comment]
i think there might be actually an issue with storing it in a variable, that is the user might not be able to see all of the possible datasets by just looking at the file, instead they'd have to print out the variable manually.

we can probably fix that by using that variable you mentioned to create a auto-gen python file

**Comment by audreymarthin** [comment]
Yes, that was what I had in mind to basically have the results written in the datasets.py.

**Comment by audreymarthin** [comment]
Yes, I think that was the approach. And I also agree with you for that issue, I will try som ehard-coded ones and the algorithmically generated ones as well. Thank you Darren!

**Comment by audreymarthin** [comment]
Hi Darren, just to give a quick update, I will be using data from https://api.census.gov/data.html. Since the title is descriptive enough, I believe we could use the title with some tweaking, making it uppercase, and adding _ as the symbolic names. In this api, there is also the api base url, so I will use that url as a reference url. Thank you!

**Comment by vengroff** [comment]
I think that is the right metadata to use. One thing to note is that metadata in the URL you pointed to is also available in JSON form at https://api.census.gov/data.json. Just change the suffix from `.html` to `.json` and you get the same information in a more machine readable form. 

This JSON version is, in fact, what the code behind the `censusdis.data.variables.all_data_sets` API does. The URL is called [here](https://github.com/vengroff/censusdis/blob/main/censusdis/impl/varsource/censusapi.py#L177). The higher level public API that converts the JSON to a data frame is [here](https://github.com/vengroff/censusdis/blob/main/censusdis/impl/varcache.py#L385). 

If you want to use this API directly so you can walk through a data frame instead of parsing HTML, take a look at cell 28 in the [tutorial notebook](https://github.com/vengroff/censusdis-tutorial/blob/main/Tutorial.ipynb) which shows how to call it and what the results look like.

**Comment by vengroff** [comment]
I think in cases where the names are the same it is almost always because they are different vintages of the same data set, and so it's fine to just have one symbolic name defined with a value set appropriately. For example, 

```
ACS5_PROFILE = 'acs/acs5/profile`
```

in the case you sighted even though there are 13 or so rows in the metadata for it, each for a different year.

I think one symbolic name for each unique value in the `DATASET` column of the dataframe returned by `censusdis.data.variables.all_data_sets` is what we should aim for.

**Comment by audreymarthin** [comment]
Thank you for the explanation, Darren!

**Comment by audreymarthin** [comment]
Hi Darren,

Just a quick update, I have already have the extended dataset. However, my current approach to get the symbolic names from your API call function and the reference link through parsing the file myself. This is because I found that your API call function didn't add the reference url field. Since I believe calling the API directly would be more efficient, I had 2 approaches in mind.

1.) I was wondering if I could just add a default field to def _datasets_from_source_dict specifically for the urls and getting the "accessURL" field from the dataset. Would that possibly break anything?
2.) The second approach is adding an optional variable for additional fields so that users can add fields according to their needs. It would be something like def _datasets_from_source_dict(datasets, additional_field: list[str] = []). I would also create an allowed_field variable, so if users input variable not in the allowed_field it would raise an error message.

I wanted to consult you which approach do you prefer in regards to this?

Thank you in advance Darren!

**Comment by vengroff** [comment]
I think number 1 is fine. Just add the new field (or multiple fields) as needed and give them appropriate names. The point of this is a dataframe for people to look through more than it is widely used programatically. And adding a column should not hurt.

**Comment by audreymarthin** [comment]
Hi Darren,

Thank you so much. Yes, that makes sense to me as well. I will get to it.

Have a good day!

**Comment by vengroff** [comment]
Linked PR and closing.
