### ISSUE TITLE
Automate censusdis.symbolic to generate censusdis.dataset 

### ISSUE THREAD

**Issue by audreymarthin** [vengroff/censusdis#150]
After a PR is merged, make censusdis.symbolic run and generate censusdis.dataset then commit it back to the rep and push. This will make sure that censusdis.dataset is always updated to it's latest version.

**Comment by audreymarthin** [comment]
Hi Darren!

I was working on this issue and ran intoo a problem with permission. So I managed to create the automate workflow and tested it through github actions on my forked repository of censusdis. However, it doesn't seem to be pushing the newly generated datasets file as expected, though it passed the test of pushing it. Could it be this is because of certain permission access? Like something related to the DEPLOY_ACTION_SECRET. Is this a secret deploy key from your repo that doesn't work on mine because I forked it? 

Thank you in advance!

**Comment by audreymarthin** [comment]
Hi Darren,

Regarding my previous comment, I tried a different approach of having a separate file with the purpose of pushing the commits made from the other 2 workflow files. However, I don't think it's actually pushing the commits from the different workflow files. So, I was wondering, do you think the best approach is:

1.) combining the automate and coverage-report into one workflow file just different jobs.
2.) still separate them to different workflow files and have coverage-report gets triggered once automate is successfully pushed. Then before pushing coverage-report's commits maybe do something like pull the changes first.

Thank you once again!

**Comment by dat-sudo** [comment]
if you create 2 jobs in a single workflow, you still have to define one job as the prerequisite of the other, otherwise those jobs will run in parallel. 

personally, i'd go with 1 because of the simplicity.
my suggestion is to create 3 jobs 
1. coverage-report 2. symbolic gen 3. push all files generated by those jobs
1 is a prereq of 2, and 2 is a prereq of 3. (order of 1 and 2 can be swapped whatever) https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow#defining-prerequisite-jobs

 in the future if you have more jobs, you could easily add them between 2 and 3.

**Comment by vengroff** [comment]
Job is ruuning.
