### ISSUE TITLE
remove_water=True in MA removes too much

### ISSUE THREAD

**Issue by vengroff** [vengroff/censusdis#212]
The code

```python
import censusdis.data as ced
from censusdis.datasets import ACS5
from censusdis.states import MA

gdf_county_remove_water = ced.download(
    ACS5,
    2020,
    ["NAME"],
    state=MA,
    county="*",
    with_geometry=True,
    remove_water=True,
)
```

produces unexpected results, with entire counties disappearing. The result looks like:

![image](https://github.com/vengroff/censusdis/assets/6465299/7b174e56-df36-4a90-8394-f0e99fa0e532)

Notice there are large areas of land where there is nothing left after removing water. Without `remove_water=True` the same thing looks like this:

![image](https://github.com/vengroff/censusdis/assets/6465299/05861e99-e5db-45a8-b36d-f87b44ddad9a)

I put the notebook `MA Remove Water Issue.ipynb` that generated both of these on the branch [`dev/ma_remove_water`](https://github.com/vengroff/censusdis/tree/dev/ma_remove_water) so you can check it out and debug it. 

You can preview the whole notebook at https://github.com/vengroff/censusdis/blob/dev/ma_remove_water/notebooks/MA%20Remove%20Water%20Issue.ipynb.

**Comment by CanyonFoot** [comment]
I have found the problem. In Mass (and presumably some other states although the ones I've checked have looked fine) there's a high density of rivers and lakes, particularly in the middle of the state. When remove the water polygons, this creates complicated multipolygons in place of the original simpler county geometries. Then, when we apply `remove_slivers` many component polygons are dropped, resulting in the missing areas. 

For instance, Worcester county is the one in middle of Mass that is getting dropped in the above example. Before we remove the water, this county has a single polygon geometry. Afterwards, the multipolygon created by dropping the water contains about 140 component polygons. Most of these are very small and don't visibly affect the map much. One polygon, however, corresponds to almost all of the original county, but with the water removed.
![image](https://github.com/vengroff/censusdis/assets/33793596/4592831a-827e-4586-82d0-3c6ed0693445)

This polygon has many areas 'cutout' from the removed water areas and as a result has an inflated `length` attribute compared to the original (something like 6X higher). When we go to calculate the isoperimetric quotient, this inflated perimeter deflates the quotient value just below our default cutoff, removing the bulk of the county.

Happily, one solution turns out to be extremely simple. Instead of taking the `length` of the geometry to calculate the isoperimetric quotient, we can first calculate the exterior of the polygon and take the length of that geometry instead. This way, we can ignore all the additional perimeter that is added by pieces of removed water. This approach should be strictly more conservative than just using length since the exterior perimeter is always less or equal to what we get with length. I'll post a PR in a few minutes making this change.
